
backgallery:
  storage:
    data-dir: "backgallery-data"
    media-dir: "media"
    store-originals: data-dir

server:
  port: 8080

management:
  security:
    enabled: false
  context-path: "/management"

spring:
  main:
    banner-mode: off
  http:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB