
storage:
  data-dir: "backgallery-data"
  media-dir: "media"
  store-originals: data-dir

management:
  security:
    enabled: false
  context-path: "/management"

spring:
  main:
    banner-mode: off
